[package]
name = "phasellus"
version = "0.3.0"
edition = "2021"
description = "A yacht game scoreboard"
license = "MIT"

[dependencies]
rustyline = { version = "11.0", features = ["signal-hook"] }
unicode-width = "0.1.10"
