[package]
name = "phasellus"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = { version = "10.0.0", features = ["signal-hook"] }
unicode-width = "0.1.10"
